name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: gcc snake.cpp -o snake.exe
    - name: make
      run: make
    - name: Run
      run: ./snake.exe
    
